name: Build

on:
  schedule:
    - cron:  '0 0/4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 12

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run a multi-line script
        run: python3 main.py
        env: 
          GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}